services:
  sumodl:
    build:
      context: .         
      dockerfile: Dockerfile  
      # The deploy was having problems with DNS when building
      network: host
    volumes:
     - "${MEDIA_DIRECTORY}:/media"
    environment:
     - MEDIA_DIRECTORY=/media
     - PATH=/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    dns:
     - 8.8.8.8
