- name: Run sumodl service 
  hosts: myhosts
  gather_facts: false
  vars:
    MEDIA_DIRECTORY: "/mnt/toshiba/media/completed/tv"
    tracked_files: "{{ lookup('pipe', 'git ls-files') | split('\n') }}"
  tasks:
    - name: Create parent directories on remote
      file:
        path: "~/sumodl/{{ item | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ tracked_files }}"
      loop_control:
        label: "{{ item | dirname }}"

    - name: Copy over files 
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~/sumodl/{{ item }}"
        mode: '0644'
      loop: "{{ tracked_files }}"
    - name: Write .env file
      copy:
        dest: "~/sumodl/.env"
        content: |
          MEDIA_DIRECTORY={{ MEDIA_DIRECTORY }}
    
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: sumodl
        state: absent

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: sumodl
        state: present
        build: "always"
      environment:
        # The deploy can't find the correct DNS to do the needed debian downloads, maybe because of tailscale.
        # Building like this fixes this, but I don't know why
        DOCKER_BUILDKIT: "0"
