- name: Run sumodl service 
  hosts: myhosts
  gather_facts: false
  tasks:
    - name: Copy over files 
      ansible.builtin.copy:
        src: .
        dest: ~/sumodl

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: sumodl
        state: absent

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: sumodl
      environment:
        MEDIA_DIRECTORY: /tmp
